### ISSUE TITLE
Doesn't work on iPhone 7 & iPhone 7 Plus

### ISSUE THREAD

**Issue by git-hwa** [NewAmsterdamLabs/ZOZolaZoomTransition#6]
It works on other device simulators, but doesn't work on iPhone7 and iPhone 7 Plus simulators.
They are not working when push view, but works when it is reverse transition.

Why does this happens?

**Comment by scalessec** [comment]
You're correct, the push animation in the demo project doesn't appear to be working in the iPhone 7/plus simulators. I just tried it on my iPhone 7 device though and it works fine. Strange.

**Comment by git-hwa** [comment]
@scalessec it seems it's Xcode 8, simulator issue.
Please let me know when you pinpoint this issue later. 👍

**Comment by scalessec** [comment]
@lubos08 I've figured it out and will push to `master` shortly. For some reason `snapshotViewAfterScreenUpdates:` renders differently on the iOS10 simulators. The workaround is to just use my `zo_snapshot` category when running in the simulator. This is strictly a simulator issue, but I want to make sure I fix it because it will probably scare people aware from using the library. Thanks for finding this.

**Comment by git-hwa** [comment]
@scalessec glad to know you've figured it out.
I really like your library and will wait for your update 👍

**Comment by scalessec** [comment]
Pushed to `master`, but I'm unable to release a new pod version until CocoaPods 1.1.0 is released (which will support XCode 8).

**Comment by lubos08** [comment]
Please let me know how can I pull the update from your master branch.

**Comment by git-hwa** [comment]
@scalessec Thanks for your update!
